# Generated by Django 3.2.9 on 2021-12-06 17:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_number', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('loading_port', models.CharField(max_length=64)),
                ('discharge_port', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('weight', models.IntegerField(verbose_name='lbs')),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.booking')),
            ],
        ),
    ]
