# Generated by Django 3.2.9 on 2021-12-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='booking',
            field=models.ForeignKey(default='6a823020-c618-4d4e-aa3f-f2c17c168a46', on_delete=django.db.models.deletion.CASCADE, to='transport.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
