# Generated by Django 3.2.9 on 2021-12-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20211206_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ship_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ship_departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
