# Generated by Django 3.2.9 on 2021-12-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20211206_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.booking'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight(lbs)'),
        ),
    ]
