# Generated by Django 3.2.9 on 2021-12-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20211208_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_vehicles',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
