# Generated by Django 3.2.9 on 2021-12-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_booking_booking_vehicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_vehicles',
        ),
    ]
